[
    {
        id: 4,
        firstname: 'Mustapha',
        lastName: 'Qomorudeen',
        email: 'adewunmi99@gmail.com',
        phone: '+2348169683067',
        address: 'No 9, Adejoke Adetola',
        city: 'Mowe',
        yearsOfExp: '2',
        feStack: '',
        beStack: '',
        mobileStack: '',
        otherStack: '',
        githubLink: 'githublink.com',
        careerGoals: 'values',
        portfolioLink: '',
        availability: 'yes',
        fellowshipInfo: '',
        resume: 'https://460624858521-nestjs-uploader.s3.amazonaws.com/Updated_Resume.pdf',
        type: 'program',
        programPreferenceID: 1,
        jobAppliedForID: null,
        applicationDate: '2023-12-01T19:58:27.610Z',
        status: 'pending',
        createdAt: '2023-12-01T19:58:27.610Z',
        updatedAt: '2023-12-01T19:58:27.610Z'
    },
    {
        id: 3,
        firstname: 'Boluwatife',
        lastName: 'Lambe',
        email: 'boluwatifelambe@gmail.com',
        phone: '+2348083647531',
        address: '6, Ogunyemi Street',
        city: 'Somolu ',
        yearsOfExp: '5',
        feStack: 'hwefbj',
        beStack: 'fdjf',
        mobileStack: 'nejnfkj',
        otherStack: 'erjbkj',
        githubLink: 'https://github.com/Uptick-Talent/team-a/pulls',
        careerGoals: 'jdbjkd',
        portfolioLink: 'https://github.com/Uptick-Talent/team-a/pulls',
        availability: 'yes',
        fellowshipInfo: 'dhfbhj',
        resume: 'https://460624858521-nestjs-uploader.s3.amazonaws.com/Screenshot (13).png',
        type: 'job',
        programPreferenceID: null,
        jobAppliedForID: 1,
        applicationDate: '2023-11-30T10:18:57.942Z',
        status: 'pending',
        createdAt: '2023-11-30T10:18:57.942Z',
        updatedAt: '2023-11-30T10:18:57.942Z'
    },
    {
        id: 2,
        firstname: 'Boluwatife',
        lastName: 'Lambe',
        email: 'boluwatifelambe@gmail.com',
        phone: '+2348083647531',
        address: '6, Ogunyemi Street',
        city: 'Somolu ',
        yearsOfExp: '5',
        feStack: 'ReactJS',
        beStack: 'NodeJS',
        mobileStack: 'Flutter',
        otherStack: 'MongoDB',
        githubLink: 'https://github.com/Uptick-Talent/team-a/pulls',
        careerGoals: 'jnwqdebjkdn q DK',
        portfolioLink: 'https://github.com/Uptick-Talent/team-a/pulls',
        availability: 'yes',
        fellowshipInfo: 'ewfjkwenkwlnew',
        resume: 'https://460624858521-nestjs-uploader.s3.amazonaws.com/Screenshot (9).png',
        type: 'program',
        programPreferenceID: 1,
        jobAppliedForID: null,
        applicationDate: '2023-11-29T22:00:51.494Z',
        status: 'pending',
        createdAt: '2023-11-29T22:00:51.494Z',
        updatedAt: '2023-11-29T22:00:51.494Z'
    }
]