import { Inter, Raleway } from 'next/font/google';
import './globals.css';
import { AuthProvider } from './Providers';
import { authOptions } from "app/api/authOptions";
import { getServerSession } from "next-auth/next"

const inter = Inter({ subsets: ['latin'] });
const raleway = Raleway({ weight: ['400', '500', '600', '700', '800', '900'], subsets: ['cyrillic', 'latin', 'vietnamese', 'cyrillic-ext', 'latin-ext'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
    const session = await getServerSession(authOptions);

    return (
        <html lang="en">
            <body className={raleway.className}>
                <AuthProvider session={session}>{children}</AuthProvider>
            </body>
        </html>
    )
}
