import { Inter, Raleway } from 'next/font/google';
import './globals.css';
import { AuthProvider } from './Providers';

const inter = Inter({ subsets: ['latin'] });
const raleway = Raleway({ weight: ['400', '500', '600', '700', '800', '900'], subsets: ['cyrillic', 'latin', 'vietnamese', 'cyrillic-ext', 'latin-ext'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={raleway.className}>
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    )
}
